services:
  php-app:
    image: edme1089/php-app:latest
    container_name: php_app_container
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: edem1089/mariadb-sample:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
    ports:
      - "3306:3306"

